Lesson4prj/urls.py
from django.contrib import admin
from django.urls import path
from less4App import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name="index"),
    path('create', views.create, name="create"),
    path('edit/<int:id>', views.edit ),
    path('update/<int:id>', views.update ),
    path('delete/<int:id>', views.destroy ),
    path('test', views.test, name="test"),
    path('send',views.email,name='send'),


]

less4App/models.py
from django.db import models

class Employee(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField("Employee Name", max_length=100)
    email = models.EmailField("Email Address", max_length=100)
    dob = models.DateTimeField("Date of Birth")
    salary = models.FloatField("Basic Salary")

    def __str__(self):
        return self.name

    class Meta:
        db_table = "employees"

less4App/forms.py
from django import forms
from .models import Employee

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = "__all__"

widgets = {
        'dob'   : forms.DateInput(attrs={'class': 'form-control datepicker1'}),
        'name'  : forms.TextInput(attrs={'class': 'form-control'}),
        'email' : forms.TextInput(attrs={'class': 'form-control','placeholder': 'Email Address'}),
        'salary': forms.TextInput(attrs={'class': 'form-control'}),

}


class ContactForm(forms.Form):
        to      = forms.EmailField(required=True,widget= forms.TextInput(attrs={'class': 'form-control col-sm-4','placeholder':'Email Address'}))
        subject = forms.CharField( required=True,widget= forms.TextInput(attrs={'class': 'form-control col-sm-4','placeholder':'Subject'}))
        message = forms.CharField( required=True,widget= forms.Textarea(attrs={'class': 'form-control col-sm-4','placeholder':'Message'}), label=(''))

less4App/views.py
from django.shortcuts import render, redirect
from .models import Employee
from less4App.forms import EmployeeForm

from django.core.paginator import Paginator
from django.contrib import messages

from less4App.forms import ContactForm
from django.core.mail import BadHeaderError
from django.core.mail import EmailMessage
# Create your views here.
def index(request):
        emp = Employee.objects.all()
        context = {'title': 'Welcome', 'employees': emp}
        return render(request,"index.html",context)

def create(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST,request.FILES)
        if form.is_valid():
            try:
                form.save()
                messages.error(request,'Insert Succesfully')
                return redirect('/')
            except:
                pass
        else:
            pass
    else:
        form = EmployeeForm()
    return render(request,"create.html",{'form':form})

def edit(request, id):
    employee = Employee.objects.get(id=id)
    form = EmployeeForm(request.POST,request.FILES)
    return render(request,'edit.html', {'employee':employee, 'form':form})

def update(request,id):
    employee = Employee.objects.get(id=id)
    form = EmployeeForm(request.POST,request.FILES,instance=employee)
    if form.is_valid():
        try:
            form.save()
            messages.error(request,'Update Succesfully')
            return redirect('/')
        except:
            pass
        else:
            messages.error(request,form.errors)
    return render(request,"edit.html",{'employee':employee,'form':form})
def destroy(request, id):
    employee = Employee.objects.get(id=id)
    employee.delete()

    return redirect("/")

def test(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST,request.FILES)
        if form.is_valid():
            try:
                form.save()
                messages.error(request,'Insert Succesfully')
                return redirect('/')
            except:
                pass
        else:
            pass
    else:
        form = EmployeeForm()
    return render(request,"test.html",{'form':form})

def email(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['to']
            message = form.cleaned_data['message']

            recipient_list = []
            recipient_list.append(from_email)
            try:
                emailobj = EmailMessage(subject, message, to=recipient_list)
                emailobj.send()
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('/')
    return render(request, "email.html", {'form': form})

less4App/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    <title>{% block title %}Title{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >

    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

    <!--for dataTables-->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.18/css/jquery.dataTables.min.css" >
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
      <!--for datepicker-->
    <link rel="stylesheet" href="   https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.css" >
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>


    {% block stylesheet %}{% endblock %}
  </head>
  <body>
    <div class="">
      <img src="{% static 'images/logo.png' %}" alt="No Image" class="fullwidth">
    </div>


<!--navbar-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Zub</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/create">Add Emp</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<main>
  <div class="container">
    {% block content %}{% endblock %}
  </div>
</main>

<script>
  $(function(){

  });

  $(function(){
    $('#emptable').DataTable({
      "dom": '<f<t>ip>', //document object model
      "lengthMenu":[[5,10, 25, 50, -1],[5,10,25,50,"All"]]

    }) //datatable end
  }); //function end

  $(document).ready(function(){
    $(".datepicker1").datepicker({
    format:"mm/dd/yyyy",
    weekStart: 0,
    calendarWeeks: true,
    autoclose: true,
    todayHighlight:true,
    rtl: true,
    
    })
  });
</script>
  {% block javascript %}{% endblock %}

  </body>
</html>

less4App/templates/create.html
{% extends 'base.html' %}

{% block title %}Create{% endblock %}
{% block stylesheet %} {% endblock %}
{% block content %}

<form  method="post" class="" action="/create">
  {% csrf_token %}
  <div class="container">

        <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
        <h3>Enter Details</h3>
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Name:</label>
        <div class="col-sm-4">
        {{form.name}} <!--textbox-->
        </div>
      </div>
        <div class="form-group row">
        <label class="col-sm-2 col-form-label">Email:</label>
        <div class="col-sm-4">
          {{form.email}}
        </div>
      </div>
        <div class="form-group row">
        <label class="col-sm-2 col-form-label">Date of birth:</label>
        <div class="col-sm-4">
            <input type="text" name="dob" value="" class="datepicker1">
        </div>
      </div>
      <div class="form-group row">
    <label class="col-sm-2 col-form-label">Salary:</label>
    <div class="col-sm-4">
        {{form.salary}}
    </div>

  </div>
        <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
        <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </div>
        </div>
    </form>
{% endblock %}

less4App/templates/edit.html
{% extends 'base.html' %}

{% block title %}Create{% endblock %}
{% block stylesheet %} {% endblock %}
{% block content %}

<form method="POST" class="post-form" action="/update/{{employee.id}}" enctype="multipart/form-data" >
  {% csrf_token %}
  <div class="container">

      {% for message in messages %}
        <div class="alert alert-danger">
          <a class="close"href="#" data-dismiss="alert">x</a>
          {{message}}
        </div>
      {% endfor %}
          <br>

        <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
        <h3>Edit Employee</h3>
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Id:</label>
        <div class="col-sm-4">
            <input type="text" name="id" id="id_id" required maxlength="20" value="{{ employee.id }}"/>
        </div>
      </div>
        <div class="form-group row">
        <label class="col-sm-2 col-form-label">Name:</label>
        <div class="col-sm-4">
            <input type="text" name="name" id="id_name" required maxlength="20" value="{{ employee.name | upper}}"/>
        </div>
      </div>
      <div class="form-group row">
      <label class="col-sm-2 col-form-label">Email:</label>
      <div class="col-sm-4">
            <input type="text" name="email" id="id_email" required maxlength="20" value="{{ employee.email }}"/>
      </div>
    </div>
      <div class="form-group row">
      <label class="col-sm-2 col-form-label">Date of birth:</label>
      <div class="col-sm-4">
            <input type="text" name="dob" id="id_dob" required maxlength="20" value="{{ employee.dob | date:"m/d/Y"}}"/>
        </div>
      </div>
      <div class="form-group row">
    <label class="col-sm-2 col-form-label">Salary:</label>
    <div class="col-sm-4">
        <input type="text" name="salary" id="id_salary" required maxlength="20" value="{{ employee.salary |floatformat:"-3" }}"/>
    </div>

  </div>
        <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
        <button type="submit" class="btn btn-primary">Update</button>
        </div>
      </div>
        </div>
    </form>
{% endblock %}

less4App/templates/email.html
{% extends 'base.html' %}
{% block title %}Email{% endblock %}
{% block content %}

<h1>Contact Us</h1>
<form method="post">
  {% csrf_token %}
  {% for field in form %}
      <div class="form-group row">
        {{field.errors}}
        <label class="col-sm-2 col-form-label" for="{{field.name}}">{{field.label_tag}}</label>
        <!-- {{field.label_tag}} -->
        {{field}}
        {% if field.help_text %}
        <p class="help">{{field.help_text|safe}}</p>
        {% endif %}

      </div>
   {% endfor %}
    <div class="form-actions">
      <button type="Submit">Send</button>

    </div>
</form>
{% endblock %}

less4App/templates/index.html
{% extends 'base.html' %}

{% block title %}Index{% endblock %}
{% block stylesheet %} {% endblock %}
{% block content %}

  <div class="">
    {% for message in messages %}
    <div class="alert alert-danger">
      <a class="close"href="#" data-dismiss="alert">x</a>
      {{message}}
    </div>
    {% endfor %}
    <br>

    <center><a href="/create" class="btn btn-primary">Add New Record</a></center>
    <br><br>

  </div>
  <table class='table table-bordered table-sm' id="emptable" data-page-length='5'>
    <thead class="thead-dark">
      <tr>
        <td>Id</td>
        <td>Name</td>
        <td>Email</td>
        <td>Actions</td>
      </tr>
    </thead>
    <tbody>
      {% for emp in employees %}
      <tr>
        <td>{{emp.id}}</td>
        <td>{{emp.name}}</td>
        <td>{{emp.email}}</td>
        <td>
          <a href="/edit/{{emp.id}}">Edit</a>
          <a href="/delete/{{emp.id}}">Delete</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <br>

{% endblock %}

  </body>
</html>

less4App/templates/test.html
{% extends 'base.html' %}

{% block title %}Index{% endblock %}

{% block content %}


{{form.as_p}}

<table>
  <button type="submit">Submit</button>
  
</table>